name: Export Wekan Image
on: [workflow_dispatch]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Clean up conflicts
        run: |
          sudo apt-get remove -y containerd || true  # 强制移除旧版
          sudo apt-get autoremove -y

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Pull Wekan Image
        run: sudo docker pull wekan/wekan:latest

      - name: Save as .tar
        run: sudo docker save -o wekan.tar wekan/wekan:latest

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wekan.tar
          path: wekan.tar
