name: Export Wekan Image
on: [workflow_dispatch]  # 允许手动触发工作流

jobs:
  export:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的 Ubuntu 服务器
    steps:
      - name: Set up Docker
        run: |  # 安装 Docker
          sudo apt update
          sudo apt install docker.io -y

      - name: Pull Wekan Image
        run: sudo docker pull wekan/wekan:latest  # 拉取镜像

      - name: Save as .tar
        run: sudo docker save -o wekan.tar wekan/wekan:latest  # 导出为.tar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3  # 上传产物
        with:
          name: wekan.tar  # 产物名称
          path: wekan.tar  # 文件路径
