name: Export Wekan Image

on:
  workflow_dispatch:  # 手动触发

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      # 1. 安装 Docker 并配置权限
      - name: Set up Docker
        run: |
          sudo apt-get update && sudo apt-get install -y docker.io
          # 将当前用户添加到 Docker 组（避免权限问题）
          sudo usermod -aG docker $USER
          newgrp docker  # 重新加载组权限
          # 验证 Docker 是否安装成功
          docker --version

      # 2. 拉取 Wekan 镜像
      - name: Pull Wekan Image
        run: |
          docker pull wekan/wekan:latest
          # 验证镜像是否存在
          docker images | grep wekan/wekan:latest

      # 3. 导出镜像为 .tar 文件（无需 sudo）
      - name: Save Image as .tar
        run: |
          docker save -o wekan.tar wekan/wekan:latest
          # 验证文件生成
          ls -lh wekan.tar

      # 4. 上传 Artifact（确保路径正确）
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wekan-image
          path: wekan.tar
          retention-days: 30  # 设置 Artifact 保留天数（默认 90 天）

      # 5. 可选：清理临时文件（避免占用空间）
      - name: Cleanup
        run: rm wekan.tar
